"""empty message

Revision ID: 0437431bfa26
Revises: e2a7747dabaa
Create Date: 2022-06-10 09:14:08.334612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0437431bfa26'
down_revision = 'e2a7747dabaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub_category', sa.Column('award', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sub_category', 'award')
    # ### end Alembic commands ###
