"""empty message

Revision ID: 307dbb8db760
Revises: b45fbe4f256f
Create Date: 2022-03-05 16:22:58.029456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '307dbb8db760'
down_revision = 'b45fbe4f256f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('number', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'number')
    # ### end Alembic commands ###
