"""empty message

Revision ID: 67adbd1765ee
Revises: 307dbb8db760
Create Date: 2022-03-05 16:24:46.113333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67adbd1765ee'
down_revision = '307dbb8db760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'number')
    # ### end Alembic commands ###
