"""empty message

Revision ID: 985b73c2b3d3
Revises: c09e33037ff4
Create Date: 2022-03-31 12:10:45.028355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '985b73c2b3d3'
down_revision = 'c09e33037ff4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('institution', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'institution')
    # ### end Alembic commands ###
