"""empty message

Revision ID: a8401c9d599e
Revises: 985b73c2b3d3
Create Date: 2022-04-14 19:40:00.760702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8401c9d599e'
down_revision = '985b73c2b3d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('testField', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'testField')
    # ### end Alembic commands ###
