"""empty message

Revision ID: a93819b43582
Revises: a8401c9d599e
Create Date: 2022-05-10 01:09:51.907694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a93819b43582'
down_revision = 'a8401c9d599e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('award', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('institution', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('picture', sa.String(length=2000), nullable=True))
    op.add_column('candidates', sa.Column('testField', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'testField')
    op.drop_column('candidates', 'picture')
    op.drop_column('candidates', 'institution')
    op.drop_column('candidates', 'award')
    # ### end Alembic commands ###
