"""empty message

Revision ID: b45fbe4f256f
Revises: 8b368fd43f31
Create Date: 2022-03-05 16:21:20.909736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b45fbe4f256f'
down_revision = '8b368fd43f31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('number', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'number')
    # ### end Alembic commands ###
