"""empty message

Revision ID: c09e33037ff4
Revises: 1226585ae581
Create Date: 2022-03-31 11:12:59.999380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c09e33037ff4'
down_revision = '1226585ae581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('picture', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'picture')
    # ### end Alembic commands ###
